name: Server Deployment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote SSH commands on Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |            
            cd /www/wwwroot/ots.lionsfortco.com/order-tracking
            git fetch origin
            git reset --hard origin/main   
            git checkout main && git pull origin main         
            pnpm install
            cd apps/api
            pnpm exec prisma generate
            pnpm exec prisma migrate deploy
            pnpm build
            cd ../web
            rm -rf .next
            pnpm build
            cd /www/wwwroot/ots.lionsfortco.com/order-tracking
            pm2 order-tracking-web
            pm2 order-tracking-api
            pm2 save